# Generated by Django 3.2.9 on 2022-08-14 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/images/profile2.png', null=True, upload_to='media/avatar/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_account_account_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_account_account_followings_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
